### ISSUE TITLE
Release 6.0

### ISSUE THREAD

**Issue by hasezoey** [szokodiakos/typegoose#365]
# (Pre)Release 6.0 

- Spec is in this description, on what should have been included in 6.0
- actual changelog below (https://github.com/szokodiakos/typegoose/issues/365#issuecomment-520108444)

## Spec

*This is a list of proposed things for v6, and the checked ones made it into v6*

- [x] #356 #373 hasezoey#7 - Continuation of branch `feature/4`, to remove the Typegoose class [E][B]
- [ ] ~~#216 hasezoey#9 - Typegoose Native support for GridFS [E][NN][hasezoey#10]~~
- [x] #186 hasezoey#6 - move `ModelOptions` to decorator `@options` [E][B]
- [x] #146 #148 #149 - allow more than just `ObjectId` on `Ref<>` or do `Ref<Class, Type>`, when possible [FP][#369]
- [x] #313 - Array for hooks [NN]
- [ ] #355 - Array Transforms - waiting for mongoose to fix the issue [FP] [https://github.com/hasezoey/typegoose/pull/29]
- [x] #333 hasezoey#11 - Discriminators [FP]
- [ ] ~~#367  - Move from TSLint to @typescript-eslint/ [E] (potentially requires code-re-style)~~ - post-pound until [vscode-eslint "integrates" it](https://github.com/microsoft/vscode-eslint/issues/726) and `@typescript-eslint` improves more
- [x] #366 - Rename InstanceType<T> to something not conflicting [E][B]
- [x] hasezoey#5 - modify get & set to be an actual prop [E][B]
- [x] hasezoey#3 - Move data.ts collections to Maps [E][B]
- [x] #48 #246 #182 - use loadClass instead of self-handling [E][B]
- [x] #28 - `this` is not set - added documentation in 6.0.0 [E]
- [ ] https://github.com/szokodiakos/typegoose/issues/381#issuecomment-521072989 - Docs & tests for custom types [E]

Tag legend:
- `[FP]` - Feature-Parity
- `[E]` - Enhancement
- `[NN]` - Not-Native (to mongoose)
- `[B]` - Breaking
- ~~striked~~ - means they wont be in 6.0.0 with reasons

## Notes

- Please note that V6 is released under `@hasezoey/typegoose@next` (pre-releases, could be considered stable)
- Because the main repo (this) is "discontinued", please checkout [hasezoey/typegoose](https://github.com/hasezoey/typegoose/tree/r6/master) for version 6

# Why a repo move?

Please look into here https://github.com/typegoose/typegoose/issues/1#issuecomment-517767760

**Comment by Ben305** [comment]
My favorites are #356 and #258 👍

**Comment by hasezoey** [comment]
#258 got removed from the spec, reasons in https://github.com/szokodiakos/typegoose/issues/258#issuecomment-518450690

**Comment by hasezoey** [comment]
The Current road-blocks for release 6.0.0 to be finished:
- as described in #355, the mongoose issue must be fixed first (release 1.9.2019?)
- reinvestigate #333 after all the changes

**Comment by hasezoey** [comment]
*This is the changelog for 6.0.0, this will be modified until 6.0.0 releases*

The Changelog got moved into https://hasezoey.github.io/typegoose/changelog

all these changes are currently released under `@hasezoey/typegoose@next`

**Comment by ChrisLahaye** [comment]
@hasezoey many thanks for maintaining this awesome project!

**Comment by B-Stefan** [comment]
@Ben305  Thanks for all the work that you already get done with Typegoos!
Saved us a lot of time! 

What do you think about adding @hasezoey as a contributor to this project? It would simplify the organization for the 6.0.0 version.

**Comment by hasezoey** [comment]
@B-Stefan collaborators cant add another collaborators, only the owner of the project can

**Comment by Ben305** [comment]
This is unfortunately true

**Comment by hasezoey** [comment]
in version 6.0.0-22 the functions in the Typegoose-Class are re-added with a deprecation warning (and just as a pass-through to the new syntax)

**Comment by hasezoey** [comment]
I think version 6 is now stable enough, with many features & bug fixes, so i think to release it on the 30.9.2019

Please know that the new releases only come out on the new repo https://github.com/typegoose/typegoose
and under the package `@typegoose/typegoose`, but pre-releases are currently in `@hasezoey/typegoose`

**Comment by hasezoey** [comment]
Closing this because Version 6.0.0 got released, under the package name `@typegoose/typegoose`

[here is the changelog](https://typegoose.github.io/typegoose/changelog#600)
